version: "3"
services:
  light_seeking:
    build: ./light_seeking
    image: khepera2_light_seeking
    network_mode: host
  obstacle_avoidance:
    build: ./obstacle_avoidance
    image: khepera2_obstacle_avoidance
    network_mode: host
  coordination:
    build: ./coordination
    image: khepera2_coordination
    network_mode: host
    depends_on:
      - light_seeking
      - obstacle_avoidance
